# Generated by Django 5.0.6 on 2024-06-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_record',
            name='deposit_update_date',
            field=models.DateField(),
        ),
    ]
