# Generated by Django 5.0.6 on 2024-06-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counteropt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='identity_card',
        ),
        migrations.RemoveField(
            model_name='cashier',
            name='employee',
        ),
        migrations.DeleteModel(
            name='deposit_record',
        ),
        migrations.RemoveField(
            model_name='sys_manage',
            name='employee',
        ),
        migrations.DeleteModel(
            name='transfer_record',
        ),
        migrations.DeleteModel(
            name='withdrawal_record',
        ),
        migrations.DeleteModel(
            name='account',
        ),
        migrations.DeleteModel(
            name='online_user',
        ),
        migrations.DeleteModel(
            name='cashier',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='sys_manage',
        ),
    ]
