# Generated by Django 5.0.6 on 2024-05-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counteropt', '0006_rename_deposit_ammount_deposit_record_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_record',
            name='auto_renew_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='deposit_record',
            name='deposit_end_date',
            field=models.DateField(null=True),
        ),
    ]
